### PR TITLE
TSE code review

### PR DESCRIPTION
**Pull request by Flakster**
This is our first submission of our NY Times Clone project to be reviewed by TSE.

See live demo [here](https://rawcdn.githack.com/Flakster/NYT-article-clone.github.io/d8cc41b9b29469744eb623fb5379e9e05e0e2f35/index.html)

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :recycle: [!! Required Changes !!] :recycle:
___
Hi @Flakster  and @simoxsimo :wave: ,
Awesome job :clap: . Code looks neat and clean, no lint error, readme is descriptive enough to provide the task of this project :raised_hands: . You guys have covered all the items that are needed to decorate the page. But some items rendering need to be fixed. And I am quite sure that you will cover them easily :sunglasses: .
___
#### Please follow the instructions below to complete this project.
___
### :spades: [Mandatory Changes] :spades: 
___
1. **navbar** -> the actual one does not contain space to its left and right. But yours one contains it. Lets fix the issue cause it will make the project look more closer to the original one. Also need some space between heading and big image.
image
2. **Scrolling** -> while i was scrolling, just saw overlapping on logo and the big picture. 
image
It is because of height: 5vh; I did height: auto; And it was fixed.
https://github.com/Flakster/NYT-article-clone.github.io/blob/ed12b31bfe94e0f61b8aab07bd97f76dd9c89a52/css/style.css#L7-L14
3. The icons are breaking their flow. And the article content is too squeezed comparing to the actual one.
image
4. The signup portion need to be a little bit right.
image
5. same for editor's pick portion above :point_up: .
image
6. The marking potion is also breaking, please fix it.
image
7. The footer portion is also squeezed.
image
___
#### Please fix the above mentioned issue and send another request. (If you find rendering is different comparing to your view and screenshot use [this](https://responsivedesignchecker.com/) link, only for desktop).
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Comment by simoxsimo** [comment]
Hello Hossain!

Thanks for reviewing our code for our pull request, just to add to that I want to inform you that we worked on the project in 1080p screen resolution and it was looking good.

The attachment below is my screenshot of the project.

screencapture-file-C-Users-BnadaM-Desktop-NYT-article-clone-github-io-index-html-2019-12-06-23_24_04

**Comment by shshamim63** [comment]
## Status :recycle: [!! Required Changes !!] :recycle:
___
Hi @Flakster  and @simoxsimo :wave: ,
Thanks for providing the the resolution. I checked on that and it seems okay, except some items. For combining work on different window size, it is causing that.
___
#### Please follow the instructions below to complete this project.
___
### :spades: [Mandatory Changes] :spades: 
___
1. The video description is missing. Please add it.
2. Footer link are broken. Please fix them too.
___
#### Please fix the above mentioned issue and send another request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Review by nikasulo — CHANGES_REQUESTED** [review]
Under review by Oluwadamilare Olusakin(TSE)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under review by Oluwadamilare Olusakin(TSE)

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Bottom part should contain links on the leftmost side.

**Comment by pelzolga123** [comment]
## Hi Team!  
#### Your project looks :+1: amazing!
One more thing is missing:
* [x] Bottom part should contain links to other articles with image previews on the leftmost side.
Right now you are missing links, just add them and project is done.
### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
